package main

//go:generate stringer -type=CommandID

// Mapping of command IDs to names is generated by stringer -- re run
// "go generate" if you change the ID list below.

type CommandID int

const (
  DONE CommandID = iota
  ERRR
  RBOD
  WHDR
  WURI
  WSTA
  SWCH
  WBOD
  BEND
)

const (
  CmdError = ERRR
  CmdGetBody = RBOD
  CmdDone = DONE
)

type command struct {
  id CommandID
  msg string
}

func createErrorCommand(err error) command {
  return command{
    id: CmdError,
    msg: err.Error(),
  }
}

func (c command) String() string {
  pfx := c.id.String()
  return pfx + c.msg
}
