// Code generated by "stringer -type=CommandID"; DO NOT EDIT

package main

import "fmt"

const _CommandID_name = "DONEERRRRBODWHDRWURIWSTASWCHWBOD"

var _CommandID_index = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32}

func (i CommandID) String() string {
	if i < 0 || i >= CommandID(len(_CommandID_index)-1) {
		return fmt.Sprintf("CommandID(%d)", i)
	}
	return _CommandID_name[_CommandID_index[i]:_CommandID_index[i+1]]
}
